version: 2.1
orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.2.0

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: cazfri
          password: doing-this-later
    working_directory: /tmp

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run test
  docker-build:
    executor: docker-executor
    steps:
      - checkout
      - docker/build:
          image: cazfri/home-controller-ui
      - run: mkdir -p images
      - run: docker save -o images/home-controller-ui.image.tar.gz cazfri/home-controller-ui
      - persist_to_workspace:
          root: images
          paths:
            - home-controller-ui.image.tar.gz
  docker-push:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: images
      - run: docker load -i images/home-controller-ui.image.tar.gz
      - docker/push:
          image: nmartinruben/home-controller-ui
          registry: docker.io
          tag: latest

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - docker-build:
          requires:
            - build
            - test
      - docker-push:
          requires:
            - docker-build
